import "../styles/globals.css"
import type { Metadata } from "next"
import { Manrope } from "next/font/google"
import AntdStyledComponentsRegistry from "@/components/AntdStyledComponentsRegistry"

// components
import { MainLayout } from "@/components"

// contexts
import UIThemeProvider from "@/context/themeProvider"
import TanstackProvider from "@/context/tanstackContext"

const manrope = Manrope({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <UIThemeProvider>
      <html lang="en">
        <body className={manrope.className}>
          <TanstackProvider>
            <AntdStyledComponentsRegistry>
              <MainLayout>{children}</MainLayout>
            </AntdStyledComponentsRegistry>
          </TanstackProvider>
        </body>
      </html>
    </UIThemeProvider>
  )
}
