import "../styles/globals.css"
import type { Metadata } from "next"
import { Manrope } from "next/font/google"
import AntdStyledComponentsRegistry from "@/components/AntdStyledComponentsRegistry"
import ThemeProvider from "@/context/themeProvider"

const manrope = Manrope({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body className={manrope.className}>
          <AntdStyledComponentsRegistry>
            {children}
          </AntdStyledComponentsRegistry>
        </body>
      </html>
    </ThemeProvider>
  )
}
